workflows:
  expo-native-build:
    name: Expo Embed Build & Publish
    max_build_duration: 60
    
    environment:
      groups:
        - expo-embed
      
      vars:
        EXPO_SDK_VERSION: "53.0.0"
        NODE_VERSION: "18"
        
      node: 18.17.0
      xcode: latest
      cocoapods: default
    
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/Library/Caches/CocoaPods
        - node_modules
        - $HOME/.gradle/caches
    
    triggering:
      events: [] # Manual trigger only
    
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
          
      - name: Expo Authentication
        script: |
          npx @expo/cli@latest whoami || echo "Using EXPO_TOKEN for authentication"
          
      - name: Build iOS with Expo CLI
        script: |
          # Build iOS locally using Expo CLI
          npx @expo/cli@latest build:ios --type archive --local
            
      - name: Build Android with Expo CLI
        script: |
          # Build Android AAB locally using Expo CLI  
          npx @expo/cli@latest build:android --type app-bundle --local
    
    artifacts:
      # Local build artifacts (no download needed)
      - "*.ipa"              # iOS build output
      - "*.aab"              # Android build output  
      - "*.apk"              # Android APK if generated
      - build/**/*.ipa       # Alternative iOS location
      - build/**/*.aab       # Alternative Android location
    
    publishing:
      # iOS TestFlight publishing
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        
      # Android Google Play Internal Track
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: false
        
      email:
        recipients:
          - kutbip@aura.services
        notify:
          success: true
          failure: true