workflows:
  expo-embed-build:
    name: Expo Embed Build & Publish
    max_build_duration: 60
    
    environment:
      groups:
        - expo-embed
      
      vars:
        EXPO_SDK_VERSION: "53.0.0"
        NODE_VERSION: "18"
        
      node: 18.17.0
      xcode: latest
      cocoapods: default
    
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/Library/Caches/CocoaPods
        - node_modules
    
    triggering:
      events: [] # Disable automatic triggers, manual start only
    
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          
      - name: Authenticate with Expo
        script: |
          # EXPO_TOKEN environment variable will automatically authenticate
          # No explicit login needed when EXPO_TOKEN is set
          npx @expo/cli@latest whoami || echo "Authentication will use EXPO_TOKEN"
          npx eas-cli@latest whoami || echo "Authentication will use EXPO_TOKEN"
          
      - name: Build for iOS (Production)
        script: |
          npx eas-cli@latest build --platform ios --profile production --non-interactive
          
      - name: Build for Android (Production)
        script: |
          npx eas-cli@latest build --platform android --profile production --non-interactive
    
    artifacts:
      - build/ios/**/*.ipa
      - build/android/**/*.aab
      - '*.ipa'
      - '*.aab'
    
    publishing:
      # iOS TestFlight publishing using environment variables
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        
      # Android Google Play Internal Track publishing  
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: false
        
      # Email notifications
      email:
        recipients:
          - kutbip@aura.services
        notify:
          success: true
          failure: true