workflows:
  expo-embed-build:
    name: Expo Embed Build & Publish
    max_build_duration: 60
    
    environment:
      groups:
        - expo-embed
      
      vars:
        EXPO_SDK_VERSION: "53.0.0"
        NODE_VERSION: "18"
        
      node: 18.17.0
      xcode: latest
      cocoapods: default
    
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/Library/Caches/CocoaPods
        - node_modules
        - $HOME/.gradle/caches
    
    triggering:
      events: [] # Manual trigger only
    
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
          
      - name: Expo Authentication
        script: |
          npx @expo/cli@latest whoami || echo "Using EXPO_TOKEN for authentication"
          
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli@latest
          
      - name: Configure EAS Project
        script: |
          npx eas-cli@latest init --force --non-interactive
          
      - name: Build iOS Locally with EAS
        script: |
          # Build iOS locally (no queue, no server)
          npx eas-cli@latest build --platform ios --profile production --local --non-interactive
            
      - name: Build Android Locally with EAS
        script: |
          # Build Android locally (no queue, no server)
          npx eas-cli@latest build --platform android --profile production --local --non-interactive
          
      - name: Verify Build Artifacts
        script: |
          # List all generated build files
          echo "=== iOS Files ==="
          find . -name "*.ipa" -type f
          echo "=== Android Files ==="
          find . -name "*.aab" -type f
          find . -name "*.apk" -type f
          echo "=== All Build Files ==="
          ls -la *.ipa *.aab *.apk 2>/dev/null || echo "Some files may be in subdirectories"
    
    artifacts:
      # Native build artifacts after prebuild
      - build/ios/ipa/*.ipa                           # iOS build output
      - android/app/build/outputs/bundle/release/*.aab # Android AAB output
      - "*.ipa"                                       # Any IPA files
      - "*.aab"                                       # Any AAB files
    
    publishing:
      # iOS TestFlight publishing
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        
      # Android Google Play Internal Track
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: false
        
      email:
        recipients:
          - kutbip@aura.services
        notify:
          success: true
          failure: true