workflows:
  expo-embed-build:
    name: Expo Embed Build & Publish
    max_build_duration: 60

    environment:
      groups:
        - expo-embed

      vars:
        EXPO_SDK_VERSION: "53.0.0"
        NODE_VERSION: "18"

      node: 18.17.0
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/Library/Caches/CocoaPods
        - node_modules
        - $HOME/.gradle/caches

    triggering:
      events: [] # Manual trigger only

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Expo prebuild (generate ios/ and android/)
        script: |
          npx expo prebuild --clean --platform all

      - name: Install iOS dependencies
        script: |
          cd ios && pod install

      # - name: Decode Android Keystore
      #   script: |
      #     mkdir -p android/app
      #     echo $ANDROID_KEYSTORE_BASE64 | base64 --decode > android/app/keystore.jks

      # - name: Build Android (AAB)
      #   script: |
      #     cd android
      #     ./gradlew bundleRelease \
      #       -Pandroid.injected.signing.store.file=keystore.jks \
      #       -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
      #       -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
      #       -Pandroid.injected.signing.key.password=$KEY_PASSWORD
      #     cd ..

      - name: Build iOS (IPA)
        script: |
          cd ios

          # Apply Swift optimization patch for Release builds
          if ! grep -q "SWIFT_OPTIMIZATION_LEVEL.*Onone" Podfile; then
            cat >> Podfile << 'EOF'

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                if config.name == 'Release'
                  config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
                end
              end
            end
          end
          EOF
          fi

          pod install

          # Find workspace/project
          WORKSPACE=$(find . -name "*.xcworkspace" -type d | head -1)
          PROJECT=$(find . -name "*.xcodeproj" -type d | head -1)

          # Prepare paths
          ARCHIVE_PATH="$(pwd)/build/app.xcarchive"
          EXPORT_PATH="$(pwd)/build/ipa"
          mkdir -p "$EXPORT_PATH"

          # Create export options plist
          cat > export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF

          # Archive
          if [ -n "$WORKSPACE" ]; then
            WORKSPACE_NAME=$(basename "$WORKSPACE")
            xcodebuild -workspace "$WORKSPACE_NAME" -scheme AuraEmbedApp -configuration Release archive -archivePath "$ARCHIVE_PATH"
          else
            PROJECT_NAME=$(basename "$PROJECT")
            xcodebuild -project "$PROJECT_NAME" -scheme AuraEmbedApp -configuration Release archive -archivePath "$ARCHIVE_PATH"
          fi

          # Export IPA
          xcodebuild -exportArchive -archivePath "$ARCHIVE_PATH" -exportPath "$EXPORT_PATH" -exportOptionsPlist export_options.plist

    artifacts:
      - ios/build/ipa/*.ipa
      # - android/app/build/outputs/bundle/release/*.aab

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER  
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false

      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
      #   submit_as_draft: false

      email:
        recipients:
          - kutbip@aura.services
        notify:
          success: true
          failure: true
