workflows:
  expo-embed-build:
    name: Expo Embed Build & Publish
    max_build_duration: 60
    
    environment:
      groups:
        - expo-embed
      
      vars:
        EXPO_SDK_VERSION: "53.0.0"
        NODE_VERSION: "18"
        
      node: 18.17.0
      xcode: latest
      cocoapods: default
    
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/Library/Caches/CocoaPods
        - node_modules
    
    triggering:
      events: [] # Manual trigger only
    
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm install --save-dev eas-cli

      - name: Authenticate with Expo
        script: |
          npx @expo/cli@latest whoami || echo "Using EXPO_TOKEN authentication"
          npx eas whoami || echo "Using EXPO_TOKEN authentication"
          
      - name: Setup iOS & Android credentials
        script: |
          # Map Codemagic env vars to what EAS expects
          export EXPO_APP_STORE_CONNECT_KEY_ID=$APP_STORE_CONNECT_KEY_IDENTIFIER
          export EXPO_APP_STORE_CONNECT_ISSUER_ID=$APP_STORE_CONNECT_ISSUER_ID
          export EXPO_APP_STORE_CONNECT_PRIVATE_KEY="$APP_STORE_CONNECT_PRIVATE_KEY"

          # Save Play Store service account key to file
          if [ ! -z "$GCLOUD_SERVICE_ACCOUNT_CREDENTIALS" ]; then
            echo $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS > google-play-key.json
          fi

      - name: Build & Publish iOS (TestFlight)
        script: |
          npx eas build --platform ios --profile production --non-interactive --auto-submit
          
      - name: Build & Publish Android (Play Internal)
        script: |
          npx eas build --platform android --profile production --non-interactive --auto-submit
    
    artifacts:
      - '*.ipa'
      - '*.aab'
    
    publishing:
      email:
        recipients:
          - kutbip@aura.services
        notify:
          success: true
          failure: true
